#!/usr/bin/env bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

OPTIONS="1.Lock\n2.Suspend\n3.Reboot"

# source configuration or use default values
if [ -f $HOME/.config/rofi-power/config ]; then
  source $HOME/.config/rofi-power/config
else
  LAUNCHER="rofi -location 3 -xoffset -15 -yoffset 30 -width 10 -dmenu -i -p command:"
  LOCKER="betterlockscreen --lock blur"
fi

# Show exit wm option if exit command is provided as an argument
if [ ${#1} -gt 0 ]; then
  OPTIONS="Exit window manager\n$OPTIONS"
fi

option=`echo -e $OPTIONS | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        eval $1
        ;;
      1.Lock)
        $LOCKER
        ;;
      2.Suspend)
        betterlockscreen -s blur
        ;;
      3.Reboot)
        systemctl reboot
        ;;
      *)
        ;;
    esac
fi
