#! /bin/sh

killall mpd &

sxhkd &

bspc monitor -d I II III IV
bspc monitor HDMI2 -d V VI

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
compton &
dunst &
mpd &
setxkbmap -option caps:super & feh --bg-center ~/dotfiles/config/i3/wallpaper.png &
