#! /bin/sh

killall mpd &

sxhkd &

bspc monitor -d I II III IV
bspc monitor HDMI2 -d V VI

bspc config border_width         3
bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Border colors
bspc config normal_border_color "#181818"
bspc config active_border_color "#181818"
bspc config focused_border_color "#ab4642"
bspc config presel_feedback_color "#dc9656"

bspc rule -a Alacritty state=floating

compton &
dunst &
mpd &
setxkbmap -option caps:super &
feh --bg-center ~/dotfiles/images/jon-snow-1920x1080.jpg &
$HOME/.config/polybar/launch.sh &
$HOME/dotfiles/scripts/setup-xinput.sh &
